### ISSUE TITLE
privacy policy doesnt exist

### ISSUE THREAD

**Issue by maxhofmanf** [RiadHak/Cooling-Down-The-Cities#56]
**Describe the bug**
the privacy policy doesnt exist 

**To Reproduce**
1. Go to '[signup](http://127.0.0.1:8000/signup/)'
![Screenshot 2023-11-20 110009](https://github.com/RiadHak/Cooling-Down-The-Cities/assets/89779391/a4ed77dc-2bd6-4a43-9d12-e6b4861c0e35)

2. Click on 'privacy policy'

3. See error
![Screenshot 2023-11-20 110025](https://github.com/RiadHak/Cooling-Down-The-Cities/assets/89779391/abd4f640-c739-4323-9e38-058b1d8ea687)

**Expected behaviour**
a private policy needs to appear

**Actual behaviour**
the template for private policy doesnt exist

**Screenshots**

**Desktop (please complete the following information):**
- Browser [chrome]

**Additional context**
ik weet niet of jullie van het bedrijf een privacy policy hebben gekregen dus even vragen

**Comment by Ionlylike1kindofcheese** [comment]
I'm on it

**Comment by Ionlylike1kindofcheese** [comment]
Issue has been fixed
